### ISSUE TITLE
oembed template tag eats </p> tags

### ISSUE THREAD

**Issue by udbhav** [ericflo/django-oembed#1]
My template is something like this:

```
{% autoescape off %}
{% oembed %}
{{ post.body }}
{% endoembed %}
{% endautoescape %}
```

post.body is:

```
<p>I love this video!</p><p>http://www.youtube.com/watch?v=LijbpDExI3A</p>
```

this is the output html:

```
<p>I love this video!</p><p><embed src='http://www.youtube.com/v/LijbpDExI3A&fs=1' allowfullscreen='true' type='application/x-shockwave-flash' wmode='transparent' width='425' height='344'></embed>>
```

As you can see, my closing p tag is gone.

**Comment by udbhav** [comment]
My apologies, I guess I could just change the provider rule to something along the lines of: 

```
http://\S*.youtube.com/watch[^\s<]*
```

**Comment by udbhav** [comment]
Haha, I was using an old version from your google code site, which had some older regexes for the provider rules given in the initial data fixtures.  Ignore me and close this issue that doesn't really exist.

**Comment by shacker** [comment]
Since the google code version isn't being kept up to date (but is still first in search results for "django oembed") please update the google code version to point to github. Just spent  time working against bugs in the old version which I didn't realize had already been fixed in this one. Thanks for the great kit.
